name: Production deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            whoami
            ls -al
            mkdir project
            cd project
            git clone https://github.com/EnnioCaprio/CICDProduction
            echo "Successful deployment"