name: Production deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: git status
      - name: Finished deployment
        run: echo "Finished process."