name: Production deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: 159.223.16.88
          key: ${{ secrets.SSH_KEY }}
          username: root

          script: |
            whoami
            ls -al
            mkdir project
            cd project
            git clone https://github.com/EnnioCaprio/CICDProduction
            echo "Successful deployment"